#!/bin/bash
#----------------------------------------------------------------------------
# Script runner for t.rexx
#
# $1 -> the test script (rexx)
# $2 -> the application to test (rexx)
#
# This script concatenates the files:
# t1 + $1 + t2 + $2 + t3
#
# and executes the resulting file.
#
# Dave Nicolette
# Version 0.0.1
# 03 Apr 2015
#----------------------------------------------------------------------------

cat t1 "${1}.rexx" t2 "${2}.rexx" t3 > t.rexx
rexx t.rexx
