#!/bin/bash
#----------------------------------------------------------------------------
# Script runner for t.rexx
#
# $1 -> the test script (rexx)
# $2 -> the application to test (rexx)
#
# This script concatenates the files:
# t1.rexx + $1 + t2.rexx + $2 + t3.rexx
#
# and executes the resulting file.
#
# Dave Nicolette
# Version 0.0.1
# 03 Apr 2015
#----------------------------------------------------------------------------

cat t1.rexx "${1}.rexx" t2.rexx "${2}.rexx" t3.rexx > t.rexx
rexx t.rexx
